version: '3.3'
services:
  yelb-ui:
    image: mreferre/yelb-ui:0.7
    ports:
      - 4454:80
    networks:
      - aj-net
    restart: always
  yelb-appserver:
    image: mreferre/yelb-appserver:0.5
    networks:
      - aj-net
    restart: always
  redis-server:
    image: redis:4.0.2
    volumes:
      - ./redis-server:/etc/redis/redis.conf
      - ./aj-vol:/data
    networks:
      - aj-net
  odilia-redis01:
    image: redis:4.0.2
    volumes:
      - ./odilia-redis01:/etc/redis/redis.conf
      - ./aj-vol1:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - aj-net
  odilia-redis02:
    image: redis:4.0.2
    volumes:
      - ./odilia-redis02:/etc/redis/redis.conf
      - ./aj-vol2:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - aj-net
  odilia-redis-sentinel01:
    image: redis:4.0.2
    volumes:
      - ./Odilia-redis-sentinel01:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - aj-net
  odilia-redis-sentinel02:
    image: redis:4.0.2
    volumes:
      - ./Odilia-redis-sentinel02:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - aj-net
  odilia-redis-sentinel03:
    image: redis:4.0.2
    volumes:
      - ./Odilia-redis-sentinel03:/etc/redis/sentinel.conf
    command: redis-sentinel /etc/redis/sentinel.conf
    networks:
      - aj-net
  yelb-db:
    image: mreferre/yelb-db:0.5
    volumes:
      - ede:/var/lib/postgresql/data
    networks:
      - aj-net
  yelb-db-replication1:
    image: mreferre/yelb-db:0.5
    volumes:
      - ede1:/var/lib/postgresql/data
    networks:
      - aj-net
  yelb-db-replication2:
    image: mreferre/yelb-db:0.5
    volumes:
      - ede2:/var/lib/postgresql/data
    networks:
      - aj-net
  yelb-db-replication3:
    image: mreferre/yelb-db:0.5
    volumes:
      - ede3:/var/lib/postgresql/data
    networks:
      - aj-net
networks:
  aj-net:
    driver: bridge
volumes:
  aj-vol:
    driver: local
  aj-vol1:
    driver: local
  aj-vol2:
    driver: local
  ede:
    driver: local
  ede1:
    driver: local
  ede2:
    driver: local
  ede3:
    driver: local
