version: 3.3
services:
  yelb-ui:
    images: mreferre/yelb-ui:0.7
    ports: 
      4454:80
    network:
      - aj-net
    restart: always
  yelb-appserver:
    images: mreferre/yelb-appserver:0.5
    network:
      - aj-net
    restart: always 
    

  redis-server:
    images: redis:4.0.2
    volumes: 
      - ./redis-server:/etc/redis/redis.conf
      - ./aj-vol:/data
    networks:
      - aj-net

  odilia-redis01:
    images: redis:4.0.2
    volumes:
      - ./odilia-redis01:/etc/redis/redis.conf
      - ./aj-vol1:/data
    command: redis-server /etc/redis/redis.conf
    networks: 
      - aj-net

  odilia-redis02:
    images: redis:4.0.2
    volumes:
      - ./odilia-redis02:/etc/redis/redis.conf
      - ./aj-vol2:/data
    command: redis-server /etc/redis/redis.conf
    networks: 
      - aj-net
  
  odilia-redis-sentinel01:
    images: redis:4.0.2
    volumes:
      - ./Odilia-redis-sentinel01:/etc/redis/sentinel.conf
    command: redis-sentinel  /etc/redis/sentinel.conf
    networks: 
      - aj-net

  odilia-redis-sentinel02:
    images: redis:4.0.2
    volumes:
      - ./Odilia-redis-sentinel02:/etc/redis/sentinel.conf
    command: redis-sentinel  /etc/redis/sentinel.conf
    networks: 
      - aj-net

  odilia-redis-sentinel03:
    images: redis:4.0.2
    volumes:
      - ./Odilia-redis-sentinel03:/etc/redis/sentinel.conf
    command: redis-sentinel  /etc/redis/sentinel.conf
    networks: 
      - aj-net

  yelb-db:
    images: mreferre/yelb-db:0.5
    volumes: 
      - ede:/var/lib/postgresql/data
    network:
      - aj-net

  yelb-db-replication1:
    images: mreferre/yelb-db:0.5
    volumes: 
      - ede1:/var/lib/postgresql/data
    network:
      - aj-net

  yelb-db-replication2:
    images: mreferre/yelb-db:0.5
    volumes: 
      - ede2:/var/lib/postgresql/data
    network:
      - aj-net

  yelb-db-replication3:
    images: mreferre/yelb-db:0.5
    volumes: 
      - ede3:/var/lib/postgresql/data
    network:
      - aj-net

network:
  aj-net
    - bridge

volumes:
  aj-vol
    - local
  aj-vol1
    - local
  
  aj-vol2
    - local

  ede

    - local
  ede1:
    - local
  ede2:
    - local
  ede3:
    - local







