version: '3.2'

services:
  ui:
    image: devopseasylearning/tarzan-ui:v0.0.1
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080 
      WEATHER_HOST: weather 
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    container_name: ui_service
    hostname: aj_server_ui
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - auth
    restart: always
    networks:
      - aj-network

  auth:
    image: devopseasylearning/tarzan-auth:v0.0.1
    container_name: auth_service
    hostname: aj_server_auth
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    expose:
      - 8080
    depends_on:
      - db
    restart: always
    networks:
      - aj-network

  weather:
    image: devopseasylearning/tarzan-weather:v0.0.1
    container_name: weather_service
    hostname: aj_server_weather
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    expose:
      - 5000
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - aj-network

  db:
    image: devopseasylearning/tarzan-db:v0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - tarzan-db-data:/var/lib/mysql/data
    restart: always
    networks:
      - aj-network

  redis:
    image: redis
    environment:
      REDIS_USER: redis 
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - aj-network

volumes:
  tarzan-db-data:
  redis-data:

networks:
  aj-network:
    driver: bridge
