version: '3.2'

services:
  ui:
    image: devopseasylearning/thomisis-ui:v0.0.1 
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080 
      WEATHER_HOST: weather 
      WEATHER_PORT: 5000
      REDIS_USER: redis
      REDIS_PASSWORD: redis
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - auth
    restart: always
    networks:
      - aj-network

  auth:
    image: devopseasylearning/thomisis-auth:v0.0.1 
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    expose:
      - 8080
    depends_on:
      - weather
    restart: always
    networks:
      - aj-network

  weather:
    image: devopseasylearning/thomisis-weather:v0.0.1
    environment:
      APIKEY: ecbc396f46mshb65cbb1f82cf334p1fcc87jsna5e962a3c542
    expose:
      - 5000
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - aj-network

  db:
    image: devopseasylearning/thomisis-db:v0.0.1 
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - thomasis-db-data:/var/lib/mysql/data
    restart: always
    networks:
      - aj-network

  redis:
    image: redis:7.2.3
    environment:
      REDIS_USER: redis 
      REDIS_PASSWORD: redis
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - aj-network

volumes:
  thomasis-db-data:
  redis-data:

network:
  aj-network:
    driver: bridge
